### ISSUE TITLE
Task #3

### ISSUE THREAD

**Issue by Arista213** [artemsuvorov/Funcan#1]
1. FunctionController вместо строки должен возвращать ActionResult<PointSet>
2. обработка ошибок в эндпоинтах
3. переименовать все классы, сервисы, методы, аргументы методов (solver в plotter в т.ч)
4. научить function controller принимать строчку функции + диапазон откуда брать значения (IFuncSolver тоже должен это понимать)
5. добавим для каждой особенности на графике отдельный end point, возвращающий ActionResult<PointSet>. если такой PointSet построить не удалось, возвращает например bad request
6. добавить особенности на графике
а) экстремумы
б) точки перегиба
в) монотонность
г) асимптоты
д) точки разрыва

7. добавить историю функций, научиться сохранять ее в словарик по id пользователя, который сохраняется в куки браузера
8. endpoint для get запроса истории функций
9. function controller дополнительно добавляет введенную функцию в список истории функций
10.  добавить юнит тесты

Фронт
11. добавить чекбоксы под особенности на графике, добавить поля ввода диапазона графика ф-ции, научиться принимать от сервера PointSet'ы 
12. добавить отображение для истории функций

**Comment by artemsuvorov** [comment]
### Task 3.1

1. пофиксить численные методы
2. переделать ендпоинты
`class Plot { List<PointSet> PointSets, Color, DrawType }`
`class PlotterInfo { string Name { get; set; } }`
(соотв. метод IPlotter'а возвращает объект Plot)
`ActionResult<List<Plot>> GetFunction(string func, 
	int from, int to, List<PlotterInfo> analysisOptions) {}`
 2.1. добавить ендпоинт взятия всех опций анализа графика 
    `List<PlotterInfo> GetAnalysisOptions() {}`

3. сделать пользовательскую историю
`class HistoryEntry { string func, int from, int to,
	List<PlotterInfo> analysisOptions }`
 3.1. добавить ендпоинт взятия истории по айди пользователя
    `List<HistoryEntry> GetHistory(/*user-id*/) {}`

4. доделать архитектуру согласно DDD
5. написать юнит тесты
